// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	domain "moneytracker/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIExpenseRepository is a mock of IExpenseRepository interface.
type MockIExpenseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIExpenseRepositoryMockRecorder
	isgomock struct{}
}

// MockIExpenseRepositoryMockRecorder is the mock recorder for MockIExpenseRepository.
type MockIExpenseRepositoryMockRecorder struct {
	mock *MockIExpenseRepository
}

// NewMockIExpenseRepository creates a new mock instance.
func NewMockIExpenseRepository(ctrl *gomock.Controller) *MockIExpenseRepository {
	mock := &MockIExpenseRepository{ctrl: ctrl}
	mock.recorder = &MockIExpenseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIExpenseRepository) EXPECT() *MockIExpenseRepositoryMockRecorder {
	return m.recorder
}

// AddExpense mocks base method.
func (m *MockIExpenseRepository) AddExpense(ctx context.Context, payload *domain.DailyExpense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExpense", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExpense indicates an expected call of AddExpense.
func (mr *MockIExpenseRepositoryMockRecorder) AddExpense(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExpense", reflect.TypeOf((*MockIExpenseRepository)(nil).AddExpense), ctx, payload)
}

// GetWeeklyExpenses mocks base method.
func (m *MockIExpenseRepository) GetWeeklyExpenses(ctx context.Context, week []string) (*domain.WeeklyExpense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeeklyExpenses", ctx, week)
	ret0, _ := ret[0].(*domain.WeeklyExpense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeeklyExpenses indicates an expected call of GetWeeklyExpenses.
func (mr *MockIExpenseRepositoryMockRecorder) GetWeeklyExpenses(ctx, week any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeeklyExpenses", reflect.TypeOf((*MockIExpenseRepository)(nil).GetWeeklyExpenses), ctx, week)
}

// DeleteExpensesByDate mocks base method.
func (m *MockIExpenseRepository) DeleteExpensesByDate(ctx context.Context, date string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpensesByDate", ctx, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpensesByDate indicates an expected call of DeleteExpensesByDate.
func (mr *MockIExpenseRepositoryMockRecorder) DeleteExpensesByDate(ctx, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpensesByDate", reflect.TypeOf((*MockIExpenseRepository)(nil).DeleteExpensesByDate), ctx, date)
}
