apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moneytracker.fullname" . }}-secret
type: Opaque
data:
    DB_SOURCE: {{ .Values.secrets.dbSource | b64enc | quote }}
    JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
    APP_LOGIN: {{ .Values.secrets.appLogin | b64enc | quote }}
    APP_PASSWORD: {{ .Values.secrets.appPassword | b64enc | quote }}
